KrowTest.Web/Models/TransactionDataViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace KrowTest.Web.Models
{
    public class TransactionDataViewModel
    {
        public int TransactionId { get; set; }
        public string Account { get; set; }
        public string Description { get; set; }
        public string CurrencyCode { get; set; }
        public decimal Ammount { get; set; }
    }
}

KrowTest.Web/Models/TransactionsViewModel.cs
using KrowTest.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace KrowTest.Web.Models
{
    public class TransactionsViewModel
    {
        public List<ValidationError> valdationErrors = new List<ValidationError>();
        public List<TransactionDataViewModel> UploadedData = new List<TransactionDataViewModel>();
    }
}

KrowTest.Web/Controllers/UploadController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KrowTest.Domain;
using KrowTest.Web.Models;
using KrowTest.Data.Models;
using KrowTest.Web.Map;

namespace KrowTest.Web.Controllers
{
    public class UploadController : Controller
    {
        // GET: Upload
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ActionName("Index")]
        public ActionResult IndexPost()
        {
            int UploadedCounter = 0;
            int TotalRows = 0;
            int LineNumber = 1;

            // domain object that will do all the work...
            TransactionInfo transactionInfo = new TransactionInfo();

            // remove all previous uploaded data
            transactionInfo.ClearDB();

            // store of all errors returned from the domain 
            List<ValidationError> valdationErrors = new List<ValidationError>();
            
            if (Request.Files.Count > 0)
            {
                var file = Request.Files[0];
  
                // loop throuh each line of the file...
                using (var reader = new StreamReader(file.InputStream))
                {
                    while (!reader.EndOfStream)
                    {
                        var line = reader.ReadLine();

                        // validate the line, if ok, insert else return a list of errors
                        var err = transactionInfo.ValidateAndInsert(LineNumber, line);

                        if (err != null)
                        {
                            valdationErrors.AddRange(err);
                        }
                        else
                        {
                            UploadedCounter++;
                        }

                        // increment line counter, used in the error list to determine where the fault is.
                        LineNumber++;
                        TotalRows++;
                    }
                }
            }

            // get a fresh list of the data from the db, not really needed but wanted show db interaction
            List<TransactionData> trans = transactionInfo.GetAllTransactionRows();

            // build-up a view-model
            TransactionsViewModel transactionsViewModel = new TransactionsViewModel();
            // store validation errors
            transactionsViewModel.valdationErrors = valdationErrors;
            // store uploaded rows           
            transactionsViewModel.UploadedData = new ConvertTransactionData().ToViewModel(trans);

            ViewBag.State = "uploaded";
            ViewBag.Uploaded = UploadedCounter;
            ViewBag.TotalRows = TotalRows;
            // return the list of errors to display on screen
            return View(transactionsViewModel);
        }

        [HttpPost]
        public ActionResult Update(List<TransactionDataViewModel> UploadedData)
        {
            // create domain object that will do all the work...
            TransactionInfo transactionInfo = new TransactionInfo();

            // map the view-model back to the model
            List<TransactionData> transactionDataList = new ConvertTransactionData().ToModel(UploadedData);

            transactionInfo.UpdateRange(transactionDataList);

            return View();
        }
    }
}

KrowTest.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Krow-test</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Krow-test", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

KrowTest.Web/Views/Upload/Index.cshtml
@model KrowTest.Web.Models.TransactionsViewModel

<section>
    <article>
        <header>
            <h2>Upload your transaction file here</h2>
        </header>

        @using (Html.BeginForm("Index", "Upload", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div style="display:inline-block">
                <span style="font-size:20px;color:blue;">1.</span><input type="file" name="file" style="display:inline-block"/>
                <span style="font-size:20px;color:blue;">2.</span><input type="submit" name="Submit" id="Submit" value="Upload" style="display:inline-block"/>
            </div>
        }

        @{if (@ViewBag.State == "uploaded")
            {
            <div>Transaction rows uploaded: @ViewBag.Uploaded of @ViewBag.TotalRows</div>

                if (Model != null && Model.valdationErrors.Count() > 0)
                {
                    <div style="padding-top:20px;">Validation Errors</div>
                    <div style="border:1px black solid">
                        @foreach (var err in Model.valdationErrors)
                        {
                            <div>@Html.DisplayFor(e => err.ErrorMessage)</div>
                        }
                    </div>
                }
                else
                {
                    <div>No errors found...</div>
                }
            }

            if (Model != null)
            {
                using (Html.BeginForm("Update", "Upload", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {

                    <div style="padding-top:20px;">Data that was uploaded to the database with NO validation errors</div>
                    <div style="border:1px black solid">
                        <table>
                            <tr>
                                <th> @Html.LabelFor(m => Model.UploadedData[0].Account)</th>
                                <th> @Html.LabelFor(m => Model.UploadedData[0].Description)</th>
                                <th> @Html.LabelFor(m => Model.UploadedData[0].CurrencyCode)</th>
                                <th> @Html.LabelFor(m => Model.UploadedData[0].Ammount)</th>
                            </tr>

                            @for (int i = 0; i < Model.UploadedData.Count; i++)
                    {
                        <tr>
                            <td>
                                @Html.HiddenFor(m => Model.UploadedData[i].TransactionId)
                                @Html.EditorFor(m => Model.UploadedData[i].Account)
                            </td>
                            <td>@Html.EditorFor(m => Model.UploadedData[i].Description)</td>
                            <td>@Html.EditorFor(m => Model.UploadedData[i].CurrencyCode)</td>
                            <td>@Html.EditorFor(m => Model.UploadedData[i].Ammount)</td>
                        </tr>
                    }

                        </table>
                        <input type="submit" value="Update" />
                    </div>
                }
            }
        }

    </article>
</section>

KrowTest.Web/Views/Upload/Update.cshtml
@{
    ViewBag.Title = "Update";
}

<h2>Updated</h2>